packages:
  - "packages/*"
  - "services/*"
overrides:
  "@trivago/prettier-plugin-sort-imports": 6.0.2
  prettier: 3.8.4
  "reflect-metadata": 0.2.2
allowBuilds:
  '@prisma/engines': true
  "@scarf/scarf": true
  prisma: true
  protobufjs: true
  unrs-resolver: true
