services:
    notifications-service:
        container_name: notifications-service
        image: razom-pay/notifications-service:dev
        build:
            context: ../..
            dockerfile: services/notifications/Dockerfile
        restart: always
        env_file:
            - .env.production.local
        ports:
            - '127.0.0.1:9102:9102'
            - '127.0.0.1:50052:50052'
        volumes:
            - ../../.logs/notifications:/var/log/services/notifications
        networks:
            - razom-pay

networks:
    razom-pay:
        external: true
