name: Publish Contracts

on:
  push:
    branches: [master]
    paths:
      - "packages/contracts/**"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
          registry-url: "https://registry.npmjs.org"

      - name: Install protoc
        run: sudo apt-get update  && sudo apt-get install -y protobuf-compiler

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm run build

      - name: Generate TS Protobuf
        run: pnpm generate

      - name: Publish package
        run: pnpm --filter @razom-pay/contracts publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
